# Generated by Django 4.0.4 on 2022-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('previousConditions', models.TextField()),
                ('cellularPhone', models.IntegerField()),
                ('zipCode', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('hasCovid', models.BooleanField(default=False)),
            ],
        ),
    ]
